[package]
name = "pkg"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "*"
colog = "*"
indicatif = "*"
temp-dir = "*"
clap = { version = "*", features = ["derive"] }
debian-packaging = "0.18.0"
